GET http://localhost:4000/api/

###
GET http://localhost:4000/api/gists/view

###

GET http://localhost:4000/api/gists/view/4

###

GET http://localhost:4000/gists/view/10

###

GET http://localhost:4000/gists/create

###

POST http://localhost:4000/gists/create

{
    "title" : "I love golang",
    "content" : "i want to learn it more",
    "writer" : 2
}
###